# Generated by Django 2.2.13 on 2020-06-14 22:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buzon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('ejecutado', models.CharField(max_length=100)),
                ('profundidad', models.FloatField()),
                ('tipo_pavimento', models.CharField(choices=[('SP', 'Sin Pavimento'), ('PR', 'Pavimento Rigido'), ('PA', 'Pavimento Asfaltico'), ('GCS', 'Graderia de concreto simple'), ('GCC', 'Graderia de concreto ciclopeo'), ('VEREDA', 'Vereda')], max_length=100)),
                ('tipo_excavacion', models.CharField(choices=[('MAQUINARIA', 'Maquinaria'), ('PULSO', 'Pulso')], max_length=100)),
                ('tipo_suelo', models.CharField(choices=[('TN', 'Terreno Normal'), ('TSR', 'Terreno Semirocoso'), ('TRF', 'Terreno Rocoso Fracturado'), ('TM', 'Terreno Mixto'), ('TR', 'Terreno Rocoso')], max_length=100)),
                ('tipo_buzon', models.CharField(choices=[('TIPO1', 'Buzon Tipo 1'), ('TIPO2', 'Buzon Tipo 2'), ('TIPO3', 'Buzon Tipo 3'), ('NORMAL', 'Buzon Normal')], max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RedSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilitacion', models.CharField(max_length=100)),
                ('nombre_pasaje_calle', models.CharField(max_length=100)),
                ('buzon_aguas_arriba', models.CharField(max_length=100)),
                ('buzon_aguas_abajo', models.CharField(max_length=100)),
                ('profundidad_aguas_arriba', models.FloatField()),
                ('profundidad_aguas_abajo', models.FloatField()),
                ('tipo_pavimento', models.CharField(choices=[('SP', 'Sin Pavimento'), ('PR', 'Pavimento Rigido'), ('PA', 'Pavimento Asfaltico'), ('GCS', 'Graderia de concreto simple'), ('GCC', 'Graderia de concreto ciclopeo'), ('VEREDA', 'Vereda')], max_length=100)),
                ('tipo_excavacion', models.CharField(choices=[('MAQUINARIA', 'Maquinaria'), ('PULSO', 'Pulso')], max_length=100)),
                ('longitud_horizontal', models.FloatField()),
                ('pendiente', models.FloatField()),
                ('longitud_real', models.FloatField()),
                ('longitud_excavacion', models.FloatField()),
                ('tipo_suelo', models.CharField(choices=[('TN', 'Terreno Normal'), ('TSR', 'Terreno Semirocoso'), ('TRF', 'Terreno Rocoso Fracturado'), ('TM', 'Terreno Mixto'), ('TR', 'Terreno Rocoso')], max_length=100)),
                ('longitud_tuberia', models.FloatField()),
                ('material_tuberia', models.CharField(choices=[('PVC-SN2', 'Tuberia PVC SN2'), ('PVC-SN4', 'Tuberia PVC SN4'), ('HDPE-SDR17', 'Tuberia HDPE SDR17')], max_length=100)),
                ('DN_tuberia', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
