# Generated by Django 2.2.13 on 2020-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzon',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='ejecutado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='profundidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='tipo_buzon',
            field=models.CharField(blank=True, choices=[('TIPO1', 'Buzon Tipo 1'), ('TIPO2', 'Buzon Tipo 2'), ('TIPO3', 'Buzon Tipo 3'), ('NORMAL', 'Buzon Normal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='tipo_excavacion',
            field=models.CharField(blank=True, choices=[('MAQUINARIA', 'Maquinaria'), ('PULSO', 'Pulso')], max_length=100),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='tipo_pavimento',
            field=models.CharField(blank=True, choices=[('SP', 'Sin Pavimento'), ('PR', 'Pavimento Rigido'), ('PA', 'Pavimento Asfaltico'), ('GCS', 'Graderia de concreto simple'), ('GCC', 'Graderia de concreto ciclopeo'), ('VEREDA', 'Vereda')], max_length=100),
        ),
        migrations.AlterField(
            model_name='buzon',
            name='tipo_suelo',
            field=models.CharField(blank=True, choices=[('TN', 'Terreno Normal'), ('TSR', 'Terreno Semirocoso'), ('TRF', 'Terreno Rocoso Fracturado'), ('TM', 'Terreno Mixto'), ('TR', 'Terreno Rocoso')], max_length=100),
        ),
    ]
