# Generated by Django 2.2.13 on 2020-06-15 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_auto_20200614_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzon',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
