# Generated by Django 2.2.13 on 2020-06-16 21:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20200615_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzon',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
